<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.2.999-cibuild0067775-alpha" />
    <PackageReference Include="Avalonia.Desktop" Version="12.2.999-cibuild0067775-alpha" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.2.999-cibuild0067775-alpha" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.2.999-cibuild0067775-alpha" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages\BasicPage.axaml.cs">
      <DependentUpon>BasicPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\GlowPage.axaml.cs">
      <DependentUpon>GlowPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\SkeletonPage.axaml.cs">
      <DependentUpon>SkeletonPage.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
